### ISSUE TITLE
Tooltip getCenter error

### ISSUE THREAD

**Issue by louMoxy** [bbecquet/Leaflet.PolylineOffset#15]
After I upgraded to the leaflet 1.3 I got the error that getCenter() was not a function triggered by leaflets tooltip. 

After a little digging, it seems that the polylineOffset is return an object with {x:..., y:...} rather than an instance of a leaflet point https://github.com/bbecquet/Leaflet.PolylineOffset/blob/master/leaflet.polylineoffset.js#L206

If I change ring to return leaflet point's this seems to fix the bug. 
`result.push(ring.map(xy => L.point(xy.x, xy.y)));`

Can you see any issue with this fix, or anything that I have missed?

**Comment by bbecquet** [comment]
Thanks for the bug report, investigation and proposed solution :)
This is apparently one of these rare cases in Leaflet code base where it needs a real class instance instead of an anonymous object. BTW this doesn't seem related to Leaflet 1.3, as I got the same error on 1.1.x

Your fix is great, I would just not use an arrow function to ensure old browser support, as this code is not transpiled.
I can do it myself quickly, or it would be nice if you proposed a PR yourself :)

**Comment by bbecquet** [comment]
Thank you, fixed in v1.1.1
